# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06644cb33c70332948b31cb6ebb1d85a208cfeddd2148321823adf82e635b656c174a2fc8516103bc1ce0e3c836b64cdf9fdf2a4d8d38f640f752901f22a0067

test:
  secret_key_base: 9d46e0533d08aa3057030ec7c64e2fb0e896c18752ba35d1d7078e844f3379099742e154fba70724f00d3424b8e07330303950401e0f0ca23ae9702c1e1d98dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
